# Keep compatibility fixes out of the fetched checkout: extension sync requires
# that checkout to remain clean at GIT_TAG.
set(ICEBERG_DUCKLAKE_BUILD_SOURCE "${CMAKE_BINARY_DIR}/ducklake-compat")
if (NOT "${DUCKDB_EXTENSION_DUCKLAKE_PATH}" STREQUAL "${ICEBERG_DUCKLAKE_BUILD_SOURCE}")
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(ICEBERG_DUCKLAKE_PREPARE "${CMAKE_CURRENT_LIST_DIR}/../scripts/prepare_ducklake.py")
  execute_process(
    COMMAND "${Python3_EXECUTABLE}" "${ICEBERG_DUCKLAKE_PREPARE}"
            "${DUCKDB_EXTENSION_DUCKLAKE_PATH}" "${ICEBERG_DUCKLAKE_BUILD_SOURCE}"
    RESULT_VARIABLE ICEBERG_DUCKLAKE_PREPARE_RESULT)
  if (NOT ICEBERG_DUCKLAKE_PREPARE_RESULT EQUAL 0)
    message(FATAL_ERROR "Failed to prepare DuckLake compatibility sources")
  endif()
  file(GLOB_RECURSE ICEBERG_DUCKLAKE_INPUTS "${DUCKDB_EXTENSION_DUCKLAKE_PATH}/src/*")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
               "${ICEBERG_DUCKLAKE_PREPARE}" ${ICEBERG_DUCKLAKE_INPUTS})
  set(DUCKDB_EXTENSION_DUCKLAKE_PATH "${ICEBERG_DUCKLAKE_BUILD_SOURCE}")
  set(DUCKDB_EXTENSION_DUCKLAKE_INCLUDE_PATH "${ICEBERG_DUCKLAKE_BUILD_SOURCE}/src/include")
endif()
